[[constraint]]
  name = "github.com/google/uuid"
  version = "0.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "v1.3"

[[constraint]]
  name = "github.com/Masterminds/squirrel"
  version = "v1.0"
