// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	AuthRequest
	AuthResponse
	GetUserRequest
	GetUserResponse
	User
	Payload
	CreateUserRequest
	CreateUserResponse
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthRequest struct {
	Login string `protobuf:"bytes,1,opt,name=login" json:"login,omitempty"`
	Pass  string `protobuf:"bytes,2,opt,name=pass" json:"pass,omitempty"`
}

func (m *AuthRequest) Reset()                    { *m = AuthRequest{} }
func (m *AuthRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()               {}
func (*AuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AuthRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *AuthRequest) GetPass() string {
	if m != nil {
		return m.Pass
	}
	return ""
}

type AuthResponse struct {
}

func (m *AuthResponse) Reset()                    { *m = AuthResponse{} }
func (m *AuthResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()               {}
func (*AuthResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetUserRequest struct {
	Login string `protobuf:"bytes,1,opt,name=login" json:"login,omitempty"`
}

func (m *GetUserRequest) Reset()                    { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()               {}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetUserRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

type GetUserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *GetUserResponse) Reset()                    { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()               {}
func (*GetUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	Login    string   `protobuf:"bytes,1,opt,name=login" json:"login,omitempty"`
	Pass     string   `protobuf:"bytes,2,opt,name=pass" json:"pass,omitempty"`
	Payload  *Payload `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
	CreateAt string   `protobuf:"bytes,4,opt,name=create_at,json=createAt" json:"create_at,omitempty"`
	Active   bool     `protobuf:"varint,5,opt,name=active" json:"active,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *User) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *User) GetPass() string {
	if m != nil {
		return m.Pass
	}
	return ""
}

func (m *User) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *User) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *User) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type Payload struct {
	CustomScript string `protobuf:"bytes,1,opt,name=custom_script,json=customScript" json:"custom_script,omitempty"`
	Url          string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Email        string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
}

func (m *Payload) Reset()                    { *m = Payload{} }
func (m *Payload) String() string            { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()               {}
func (*Payload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Payload) GetCustomScript() string {
	if m != nil {
		return m.CustomScript
	}
	return ""
}

func (m *Payload) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Payload) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreateUserRequest struct {
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type CreateUserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *CreateUserResponse) Reset()                    { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()               {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "auth.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "auth.AuthResponse")
	proto.RegisterType((*GetUserRequest)(nil), "auth.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "auth.GetUserResponse")
	proto.RegisterType((*User)(nil), "auth.User")
	proto.RegisterType((*Payload)(nil), "auth.Payload")
	proto.RegisterType((*CreateUserRequest)(nil), "auth.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "auth.CreateUserResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AuthBasic service

type AuthBasicClient interface {
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
}

type authBasicClient struct {
	cc *grpc.ClientConn
}

func NewAuthBasicClient(cc *grpc.ClientConn) AuthBasicClient {
	return &authBasicClient{cc}
}

func (c *authBasicClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := grpc.Invoke(ctx, "/auth.AuthBasic/Auth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authBasicClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := grpc.Invoke(ctx, "/auth.AuthBasic/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authBasicClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := grpc.Invoke(ctx, "/auth.AuthBasic/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthBasic service

type AuthBasicServer interface {
	Auth(context.Context, *AuthRequest) (*AuthResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
}

func RegisterAuthBasicServer(s *grpc.Server, srv AuthBasicServer) {
	s.RegisterService(&_AuthBasic_serviceDesc, srv)
}

func _AuthBasic_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthBasicServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthBasic/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthBasicServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthBasic_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthBasicServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthBasic/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthBasicServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthBasic_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthBasicServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthBasic/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthBasicServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthBasic_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthBasic",
	HandlerType: (*AuthBasicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _AuthBasic_Auth_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _AuthBasic_GetUser_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _AuthBasic_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0xca, 0xd3, 0x40,
	0x14, 0x25, 0xfd, 0xf2, 0xb5, 0xcd, 0xed, 0x8f, 0xf6, 0x5a, 0x6d, 0x88, 0x56, 0xcb, 0x88, 0x5a,
	0x5c, 0x34, 0xb4, 0x0a, 0x82, 0xbb, 0xea, 0xc2, 0x8d, 0x0b, 0x89, 0xe8, 0x4e, 0xca, 0x34, 0x0e,
	0xe9, 0x40, 0x9a, 0x89, 0x99, 0x49, 0x41, 0xc4, 0x8d, 0x0f, 0xe0, 0xc6, 0xa5, 0x8f, 0xe5, 0x2b,
	0xf8, 0x20, 0x32, 0x3f, 0x6a, 0x6a, 0x41, 0xba, 0x9b, 0x7b, 0xe6, 0xdc, 0x73, 0xcf, 0xdc, 0x33,
	0x30, 0x90, 0xac, 0x3a, 0xf0, 0x94, 0x2d, 0xca, 0x4a, 0x28, 0x81, 0x3e, 0xad, 0xd5, 0x2e, 0xba,
	0x95, 0x09, 0x91, 0xe5, 0x2c, 0xa6, 0x25, 0x8f, 0x69, 0x51, 0x08, 0x45, 0x15, 0x17, 0x85, 0xb4,
	0x1c, 0xf2, 0x04, 0x7a, 0xeb, 0x5a, 0xed, 0x12, 0xf6, 0xa1, 0x66, 0x52, 0xe1, 0x18, 0x2e, 0x73,
	0x91, 0xf1, 0x22, 0xf4, 0x66, 0xde, 0x3c, 0x48, 0x6c, 0x81, 0x08, 0x7e, 0x49, 0xa5, 0x0c, 0x5b,
	0x06, 0x34, 0x67, 0x32, 0x84, 0xbe, 0x6d, 0x94, 0xa5, 0x28, 0x24, 0x23, 0xf7, 0x61, 0xf8, 0x82,
	0xa9, 0x37, 0x92, 0x55, 0xff, 0xd5, 0x22, 0x4b, 0xb8, 0xf2, 0x87, 0x67, 0x5b, 0xf1, 0x36, 0xf8,
	0xb5, 0x64, 0x95, 0xe1, 0xf5, 0x56, 0xb0, 0xd0, 0xb6, 0x17, 0x86, 0x61, 0x70, 0xf2, 0xd5, 0x03,
	0x5f, 0x97, 0xe7, 0xbb, 0xc3, 0x07, 0xd0, 0x29, 0xe9, 0xc7, 0x5c, 0xd0, 0xf7, 0xe1, 0x85, 0x51,
	0x1d, 0x58, 0xd5, 0x57, 0x16, 0x4c, 0x7e, 0xdf, 0xe2, 0x4d, 0x08, 0xd2, 0x8a, 0x51, 0xc5, 0x36,
	0x54, 0x85, 0xbe, 0x51, 0xe8, 0x5a, 0x60, 0xad, 0xf0, 0x06, 0xb4, 0x69, 0xaa, 0xf8, 0x81, 0x85,
	0x97, 0x33, 0x6f, 0xde, 0x4d, 0x5c, 0x45, 0xde, 0x42, 0xc7, 0x09, 0xe1, 0x5d, 0x18, 0xa4, 0xb5,
	0x54, 0x62, 0xbf, 0x91, 0x69, 0xc5, 0x4b, 0xe5, 0xac, 0xf5, 0x2d, 0xf8, 0xda, 0x60, 0x78, 0x15,
	0x2e, 0xea, 0x2a, 0x77, 0x06, 0xf5, 0x51, 0xbf, 0x84, 0xed, 0x29, 0xcf, 0x8d, 0xbb, 0x20, 0xb1,
	0x05, 0xb9, 0x06, 0xa3, 0xe7, 0x66, 0x76, 0x63, 0x8d, 0xe4, 0x31, 0x60, 0x13, 0x3c, 0x6f, 0x67,
	0xab, 0xef, 0x2d, 0x08, 0x74, 0x3e, 0xcf, 0xa8, 0xe4, 0x29, 0xbe, 0x04, 0x5f, 0x17, 0x38, 0xb2,
	0xbc, 0x46, 0xe2, 0x11, 0x36, 0x21, 0x97, 0xe5, 0xf4, 0xcb, 0x8f, 0x9f, 0xdf, 0x5a, 0x13, 0x82,
	0xe6, 0xd3, 0x1c, 0x96, 0xb1, 0xa6, 0xc4, 0x5b, 0x2d, 0xf5, 0xd4, 0x7b, 0x88, 0xef, 0xa0, 0xe3,
	0x22, 0xc4, 0xb1, 0xed, 0x3e, 0x4e, 0x3e, 0xba, 0xfe, 0x0f, 0xea, 0x64, 0xef, 0x19, 0xd9, 0x3b,
	0x38, 0x3d, 0x92, 0xd5, 0x76, 0xe3, 0x8c, 0xa9, 0xf8, 0x93, 0x89, 0xf3, 0x33, 0x52, 0x80, 0xbf,
	0x0f, 0xc6, 0x89, 0xd5, 0x3a, 0xd9, 0x4b, 0x14, 0x9e, 0x5e, 0xb8, 0x39, 0x33, 0x33, 0x27, 0xc2,
	0xf0, 0x74, 0x8e, 0x8d, 0x76, 0xdb, 0x36, 0x9f, 0xff, 0xd1, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x2a, 0x9c, 0x26, 0xdc, 0x31, 0x03, 0x00, 0x00,
}
