// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/service.proto

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	api/service.proto

It has these top-level messages:
	AuthRequest
	AuthResponse
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthRequest struct {
	Login string `protobuf:"bytes,1,opt,name=login" json:"login,omitempty"`
	Pass  string `protobuf:"bytes,2,opt,name=pass" json:"pass,omitempty"`
}

func (m *AuthRequest) Reset()                    { *m = AuthRequest{} }
func (m *AuthRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()               {}
func (*AuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AuthRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *AuthRequest) GetPass() string {
	if m != nil {
		return m.Pass
	}
	return ""
}

type AuthResponse struct {
}

func (m *AuthResponse) Reset()                    { *m = AuthResponse{} }
func (m *AuthResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()               {}
func (*AuthResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*AuthRequest)(nil), "auth.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "auth.AuthResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AuthBasic service

type AuthBasicClient interface {
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type authBasicClient struct {
	cc *grpc.ClientConn
}

func NewAuthBasicClient(cc *grpc.ClientConn) AuthBasicClient {
	return &authBasicClient{cc}
}

func (c *authBasicClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := grpc.Invoke(ctx, "/auth.AuthBasic/Auth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthBasic service

type AuthBasicServer interface {
	Auth(context.Context, *AuthRequest) (*AuthResponse, error)
}

func RegisterAuthBasicServer(s *grpc.Server, srv AuthBasicServer) {
	s.RegisterService(&_AuthBasic_serviceDesc, srv)
}

func _AuthBasic_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthBasicServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthBasic/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthBasicServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthBasic_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthBasic",
	HandlerType: (*AuthBasicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _AuthBasic_Auth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/service.proto",
}

func init() { proto.RegisterFile("api/service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49,
	0x2c, 0x2d, 0xc9, 0x90, 0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0xc9, 0x27, 0xe6,
	0xe5, 0xe5, 0x97, 0x24, 0x96, 0x64, 0xe6, 0xe7, 0x15, 0x43, 0xd4, 0x28, 0x99, 0x73, 0x71, 0x3b,
	0x96, 0x96, 0x64, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x89, 0x70, 0xb1, 0xe6, 0xe4,
	0xa7, 0x67, 0xe6, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x38, 0x42, 0x42, 0x5c, 0x2c,
	0x05, 0x89, 0xc5, 0xc5, 0x12, 0x4c, 0x60, 0x41, 0x30, 0x5b, 0x89, 0x8f, 0x8b, 0x07, 0xa2, 0xb1,
	0xb8, 0x20, 0x3f, 0xaf, 0x38, 0xd5, 0x28, 0x92, 0x8b, 0x13, 0xc4, 0x77, 0x4a, 0x2c, 0xce, 0x4c,
	0x16, 0xf2, 0xe1, 0x62, 0x01, 0x71, 0x84, 0x04, 0xf5, 0x40, 0x4e, 0xd0, 0x43, 0xb2, 0x41, 0x4a,
	0x08, 0x59, 0x08, 0xa2, 0x57, 0x49, 0xb6, 0xe9, 0xf2, 0x93, 0xc9, 0x4c, 0xe2, 0x4a, 0x42, 0x60,
	0x47, 0x96, 0x19, 0xea, 0x83, 0x94, 0xe8, 0x27, 0x81, 0x8c, 0xb2, 0x62, 0xd4, 0x4a, 0x62, 0x03,
	0x3b, 0xd5, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x5b, 0x65, 0xc2, 0xe3, 0x00, 0x00, 0x00,
}
